"""Repository for Talk-to-Buddy realtime voice sessions (#612).

Tracks one row per session: who, when, how long, how it ended. Audio
bytes are NEVER stored — only the safety-moderated transcript score
is kept for audit. The WS broker (#615) uses ``sum_seconds_in_window``
to enforce the rolling-24h voice quota.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Optional
from uuid import uuid4

from .connection import db_manager


# How `ended_reason` can be set. Mirrored in PRD §3.16.4. The repository
# does not enforce the enum — the WS broker writes whichever value it
# determined at close time — but consumers can rely on this set being
# the canonical taxonomy.
TERMINATION_REASONS: frozenset[str] = frozenset({
    "user_ended",
    "client_disconnect",
    "timeout",
    "quota",
    "safety_fail",
    "provider_error",
    "consent_revoked",
})


@dataclass
class VoiceSessionData:
    session_id: str
    user_id: str
    child_id: str
    started_at: str
    ended_at: Optional[str]
    duration_seconds: Optional[int]
    transcript_safety_score: Optional[float]
    termination_reason: Optional[str]
    provider: Optional[str]
    # Cost-telemetry columns (#648) — populated only for OpenAI sessions.
    # Hybrid / Mock sessions leave these as None; the broker computes
    # cost_estimate_usd at end_session time from the provider's model.
    model: Optional[str] = None
    cost_estimate_usd: Optional[float] = None
    prompt_cache_hit: Optional[bool] = None


class VoiceSessionRepository:
    """CRUD + quota helpers, scoped by account owner."""

    def __init__(self, db=None):
        self._db = db if db is not None else db_manager

    async def create_session(
        self,
        *,
        user_id: str,
        child_id: str,
        provider: Optional[str] = None,
        session_id: Optional[str] = None,
    ) -> VoiceSessionData:
        """Create a new session row marked as started now.

        ``session_id`` is generated by default; callers may pass one
        explicitly (e.g. when the ephemeral token already encoded it).
        """
        now = datetime.now().isoformat()
        resolved_session_id = session_id or f"voice_sess_{uuid4().hex[:16]}"
        await self._db.execute(
            """
            INSERT INTO voice_sessions
                (session_id, user_id, child_id, started_at, ended_at,
                 duration_seconds, transcript_safety_score,
                 termination_reason, provider)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                resolved_session_id,
                user_id,
                child_id,
                now,
                None,
                None,
                None,
                None,
                provider,
            ),
        )
        await self._db.commit()
        return VoiceSessionData(
            session_id=resolved_session_id,
            user_id=user_id,
            child_id=child_id,
            started_at=now,
            ended_at=None,
            duration_seconds=None,
            transcript_safety_score=None,
            termination_reason=None,
            provider=provider,
        )

    async def end_session(
        self,
        *,
        session_id: str,
        reason: str,
        duration_seconds: Optional[int] = None,
        safety_score: Optional[float] = None,
        model: Optional[str] = None,
        cost_estimate_usd: Optional[float] = None,
        prompt_cache_hit: Optional[bool] = None,
    ) -> Optional[VoiceSessionData]:
        """Close out a session row. Idempotent — second call is a no-op.

        ``model`` / ``cost_estimate_usd`` / ``prompt_cache_hit`` are the
        #648 cost-telemetry fields. They are optional so the pre-#648
        Hybrid / Mock paths still call ``end_session`` with the same
        positional kwargs.
        """
        existing = await self.get_by_id(session_id)
        if existing is None:
            return None
        if existing.ended_at is not None:
            # Already closed — surface the canonical row without mutating.
            return existing

        now = datetime.now().isoformat()
        cache_hit_int = (
            None if prompt_cache_hit is None
            else (1 if prompt_cache_hit else 0)
        )
        await self._db.execute(
            """
            UPDATE voice_sessions
            SET ended_at = ?,
                duration_seconds = ?,
                transcript_safety_score = ?,
                termination_reason = ?,
                model = ?,
                cost_estimate_usd = ?,
                prompt_cache_hit = ?
            WHERE session_id = ?
            """,
            (
                now, duration_seconds, safety_score, reason,
                model, cost_estimate_usd, cache_hit_int,
                session_id,
            ),
        )
        await self._db.commit()
        return await self.get_by_id(session_id)

    async def get_by_id(self, session_id: str) -> Optional[VoiceSessionData]:
        row = await self._db.fetchone(
            """
            SELECT session_id, user_id, child_id, started_at, ended_at,
                   duration_seconds, transcript_safety_score,
                   termination_reason, provider,
                   model, cost_estimate_usd, prompt_cache_hit
            FROM voice_sessions
            WHERE session_id = ?
            """,
            (session_id,),
        )
        return self._row_to_data(row) if row else None

    async def list_for_child(
        self,
        *,
        user_id: str,
        child_id: str,
        limit: int = 50,
    ) -> list[VoiceSessionData]:
        rows = await self._db.fetchall(
            """
            SELECT session_id, user_id, child_id, started_at, ended_at,
                   duration_seconds, transcript_safety_score,
                   termination_reason, provider,
                   model, cost_estimate_usd, prompt_cache_hit
            FROM voice_sessions
            WHERE user_id = ? AND child_id = ?
            ORDER BY started_at DESC
            LIMIT ?
            """,
            (user_id, child_id, int(limit)),
        )
        return [self._row_to_data(row) for row in rows]

    async def sum_seconds_in_window(
        self,
        *,
        user_id: str,
        child_id: str,
        since_iso: str,
    ) -> int:
        """Return the total ``duration_seconds`` for the (user, child)
        in sessions that started at or after ``since_iso``.

        ``since_iso`` is an ISO-8601 timestamp string. Sessions still in
        flight (``ended_at`` IS NULL) contribute 0 — they're not yet
        accountable. The WS broker should re-check between utterances
        using the running clock if it wants live debit.
        """
        row = await self._db.fetchone(
            """
            SELECT COALESCE(SUM(duration_seconds), 0) AS total_seconds
            FROM voice_sessions
            WHERE user_id = ?
              AND child_id = ?
              AND started_at >= ?
              AND duration_seconds IS NOT NULL
            """,
            (user_id, child_id, since_iso),
        )
        if not row:
            return 0
        total = row.get("total_seconds", 0) or 0
        return int(total)

    @classmethod
    def _row_to_data(cls, row: dict) -> VoiceSessionData:
        cache_raw = row.get("prompt_cache_hit")
        if cache_raw is None:
            cache_hit: Optional[bool] = None
        else:
            cache_hit = bool(cache_raw)
        cost = row.get("cost_estimate_usd")
        return VoiceSessionData(
            session_id=row["session_id"],
            user_id=row["user_id"],
            child_id=row["child_id"],
            started_at=row["started_at"],
            ended_at=row.get("ended_at"),
            duration_seconds=row.get("duration_seconds"),
            transcript_safety_score=row.get("transcript_safety_score"),
            termination_reason=row.get("termination_reason"),
            provider=row.get("provider"),
            model=row.get("model"),
            cost_estimate_usd=(float(cost) if cost is not None else None),
            prompt_cache_hit=cache_hit,
        )


voice_session_repo = VoiceSessionRepository()
